Update VSCode.yml

diff --git a/.github/workflows/VSCode.yml b/.github/workflows/VSCode.yml
--- a/.github/workflows/VSCode.yml
+++ b/.github/workflows/VSCode.yml
@@ -45,10 +45,29 @@ jobs:
           REPO_ROOT="$GITHUB_WORKSPACE"
           chmod +x "$GITHUB_WORKSPACE/.github/workflows/vcpkg_build.sh"
 
+          set +x
+
           mapfile -t solutions < <(find ./bsp_repo/SampleCode -name '*.csolution.yml')
-          for sol in "${solutions[@]}"; do
-            $REPO_ROOT/.github/workflows/vcpkg_build.sh $sol
+
+          for sol_path in "${solutions[@]}"; do
+            sol_dir=$(dirname "$sol_path")
+            sol_name=$(basename "$sol_path")
+            log_path="$sol_dir/$sol_name.txt"
+
+            $REPO_ROOT/.github/workflows/vcpkg_build.sh "$sol_path" > $log_path
+            ret=$?
+
+            if [[ $ret -ne 0 ]]; then
+              echo "❌ Build failed: $sol_path"
+              echo "🔍 Log:"
+              cat "$log_path"
+            else
+              echo "✅ Build success: $sol_path"
+            fi
+            
           done
+
+          set -x
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
